name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Trigger on push to main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate 3D Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Generate Languages Stat
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

      - name: Generate Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
